### ISSUE TITLE
Failed to install under Windows

### ISSUE THREAD

**Issue by vladimmi** [nkt/node-zephir-parser#1]
```
> ./install

"." не является внутренней или внешней командой, исполняемой программой или пакетным файлом.
```

npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'zephir' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'zephir', null ]
6 verbose cache add spec zephir
7 silly cache add parsed spec { raw: 'zephir',
7 silly cache add   scope: null,
7 silly cache add   name: 'zephir',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed zephir@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'zephir', range: '*', hasData: false }
12 silly mapToRegistry name zephir
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/zephir
16 verbose addNameRange registry:https://registry.npmjs.org/zephir not in flight; fetching
17 verbose request uri https://registry.npmjs.org/zephir
18 verbose request no auth needed
19 info attempt registry request try #1 at 19:15:32
20 verbose request using bearer token for auth
21 verbose request id 4693212c52ac8c1a
22 http request GET https://registry.npmjs.org/zephir
23 http 200 https://registry.npmjs.org/zephir
24 silly get cb [ 200,
24 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 silly get     etag: '"46F1VIBUXH1PQYLXBVE3O8C1Y"',
24 silly get     'content-type': 'application/json',
24 silly get     'cache-control': 'max-age=60',
24 silly get     'content-length': '4840',
24 silly get     'accept-ranges': 'bytes',
24 silly get     date: 'Mon, 25 May 2015 16:15:35 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-fra1228-FRA',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1432570535.438247,VS0,VE429',
24 silly get     vary: 'Accept' } ]
25 verbose get saving zephir to C:\Users\Владимир\AppData\Roaming\npm-cache\registry.npmjs.org\zephir\.cache.json
26 silly addNameRange number 2 { name: 'zephir', range: '*', hasData: true }
27 silly addNameRange versions [ 'zephir', [ '0.1.0', '0.1.1', '0.1.2', '0.1.3' ] ]
28 verbose addNamed zephir@0.1.3
29 silly addNamed semver.valid 0.1.3
30 silly addNamed semver.validRange 0.1.3
31 silly mapToRegistry name zephir
32 silly mapToRegistry using default registry
33 silly mapToRegistry registry https://registry.npmjs.org/
34 silly mapToRegistry uri https://registry.npmjs.org/zephir
35 verbose addRemoteTarball https://registry.npmjs.org/zephir/-/zephir-0.1.3.tgz not in flight; adding
36 verbose addRemoteTarball [ 'https://registry.npmjs.org/zephir/-/zephir-0.1.3.tgz',
36 verbose addRemoteTarball   '4659315b75a5e845a16185ebcecfaae3b6f36fa1' ]
37 info retry fetch attempt 1 at 19:15:32
38 info attempt registry request try #1 at 19:15:32
39 http fetch GET https://registry.npmjs.org/zephir/-/zephir-0.1.3.tgz
40 verbose request using bearer token for auth
41 http fetch 200 https://registry.npmjs.org/zephir/-/zephir-0.1.3.tgz
42 silly fetchAndShaCheck shasum 4659315b75a5e845a16185ebcecfaae3b6f36fa1
43 verbose addTmpTarball C:\Users\18EE~1\AppData\Local\Temp\npm-6784-583bd551\registry.npmjs.org\zephir\-\zephir-0.1.3.tgz not in flight; adding
44 verbose addTmpTarball already have metadata; skipping unpack for zephir@0.1.3
45 silly cache afterAdd zephir@0.1.3
46 verbose afterAdd C:\Users\Владимир\AppData\Roaming\npm-cache\zephir\0.1.3\package\package.json not in flight; writing
47 verbose afterAdd C:\Users\Владимир\AppData\Roaming\npm-cache\zephir\0.1.3\package\package.json written
48 silly install resolved [ { name: 'zephir',
48 silly install resolved     version: '0.1.3',
48 silly install resolved     description: 'Zephir parser bindings',
48 silly install resolved     main: 'index.js',
48 silly install resolved     scripts:
48 silly install resolved      { prepublish: 'npm run build',
48 silly install resolved        postinstall: './install',
48 silly install resolved        build: './build' },
48 silly install resolved     repository:
48 silly install resolved      { type: 'git',
48 silly install resolved        url: 'git@github.com:nkt/node-zephir-parser.git' },
48 silly install resolved     keywords: [ 'zephir', 'parser' ],
48 silly install resolved     author: { name: 'Nikita Gusakov' },
48 silly install resolved     license: 'MIT',
48 silly install resolved     bugs: { url: 'https://github.com/nkt/node-zephir-parser/issues' },
48 silly install resolved     homepage: 'https://github.com/nkt/node-zephir-parser',
48 silly install resolved     gitHead: 'cdfe97eeba2417ae3e5515d51e88497d6f9024da',
48 silly install resolved     _id: 'zephir@0.1.3',
48 silly install resolved     _shasum: '4659315b75a5e845a16185ebcecfaae3b6f36fa1',
48 silly install resolved     _from: 'zephir@*',
48 silly install resolved     _npmVersion: '2.7.6',
48 silly install resolved     _nodeVersion: '0.12.2',
48 silly install resolved     _npmUser: { name: 'hell0w0wrd', email: 'gusnkt@gmail.com' },
48 silly install resolved     maintainers: [ [Object] ],
48 silly install resolved     dist:
48 silly install resolved      { shasum: '4659315b75a5e845a16185ebcecfaae3b6f36fa1',
48 silly install resolved        tarball: 'http://registry.npmjs.org/zephir/-/zephir-0.1.3.tgz' },
48 silly install resolved     directories: {},
48 silly install resolved     _resolved: 'https://registry.npmjs.org/zephir/-/zephir-0.1.3.tgz' } ]
49 info install zephir@0.1.3 into C:\Users\Владимир\AppData\Roaming\npm
50 info installOne zephir@0.1.3
51 verbose installOne of zephir to C:\Users\Владимир\AppData\Roaming\npm not in flight; installing
52 verbose lock using C:\Users\Владимир\AppData\Roaming\npm-cache\_locks\zephir-9b7e4a4beba5c770.lock for C:\Users\Владимир\AppData\Roaming\npm\node_modules\zephir
53 silly install write writing zephir 0.1.3 to C:\Users\Владимир\AppData\Roaming\npm\node_modules\zephir
54 silly cache addNamed cb zephir@0.1.3
55 verbose unbuild node_modules\zephir
56 verbose gentlyRm vacuuming C:\Users\Владимир\AppData\Roaming\npm\node_modules\zephir
57 verbose tar unpack C:\Users\Владимир\AppData\Roaming\npm-cache\zephir\0.1.3\package.tgz
58 verbose tar unpacking to C:\Users\Владимир\AppData\Roaming\npm\node_modules\zephir
59 verbose gentlyRm vacuuming C:\Users\Владимир\AppData\Roaming\npm\node_modules\zephir
60 silly gunzTarPerm modes [ '777', '666' ]
61 silly gunzTarPerm extractEntry package.json
62 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
63 silly gunzTarPerm extractEntry .npmignore
64 silly gunzTarPerm modified mode [ '.npmignore', 420, 438 ]
65 silly gunzTarPerm extractEntry README.md
66 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
67 silly gunzTarPerm extractEntry index.js
68 silly gunzTarPerm modified mode [ 'index.js', 420, 438 ]
69 silly gunzTarPerm extractEntry .editorconfig
70 silly gunzTarPerm modified mode [ '.editorconfig', 420, 438 ]
71 silly gunzTarPerm extractEntry install
72 silly gunzTarPerm modified mode [ 'install', 493, 511 ]
73 silly gunzTarPerm extractEntry parser/parser.h
74 silly gunzTarPerm modified mode [ 'parser/parser.h', 420, 438 ]
75 silly gunzTarPerm extractEntry parser/base.c
76 silly gunzTarPerm modified mode [ 'parser/base.c', 420, 438 ]
77 silly gunzTarPerm extractEntry parser/lemon
78 silly gunzTarPerm modified mode [ 'parser/lemon', 493, 511 ]
79 silly gunzTarPerm extractEntry parser/lemon.c
80 silly gunzTarPerm modified mode [ 'parser/lemon.c', 420, 438 ]
81 silly gunzTarPerm extractEntry parser/lempar.c
82 silly gunzTarPerm modified mode [ 'parser/lempar.c', 420, 438 ]
83 silly gunzTarPerm extractEntry parser/parser.c
84 silly gunzTarPerm modified mode [ 'parser/parser.c', 420, 438 ]
85 silly gunzTarPerm extractEntry parser/buildWin32.bat
86 silly gunzTarPerm modified mode [ 'parser/buildWin32.bat', 420, 438 ]
87 silly gunzTarPerm extractEntry parser/parser.lemon
88 silly gunzTarPerm modified mode [ 'parser/parser.lemon', 420, 438 ]
89 silly gunzTarPerm extractEntry parser/scanner.c
90 silly gunzTarPerm modified mode [ 'parser/scanner.c', 420, 438 ]
91 silly gunzTarPerm extractEntry parser/scanner.h
92 silly gunzTarPerm modified mode [ 'parser/scanner.h', 420, 438 ]
93 silly gunzTarPerm extractEntry parser/scanner.re
94 silly gunzTarPerm modified mode [ 'parser/scanner.re', 420, 438 ]
95 silly gunzTarPerm extractEntry parser/xx.h
96 silly gunzTarPerm modified mode [ 'parser/xx.h', 420, 438 ]
97 info preinstall zephir@0.1.3
98 silly install resolved []
99 verbose about to build C:\Users\Владимир\AppData\Roaming\npm\node_modules\zephir
100 info build C:\Users\Владимир\AppData\Roaming\npm\node_modules\zephir
101 verbose linkStuff [ true,
101 verbose linkStuff   'C:\\Users\\Владимир\\AppData\\Roaming\\npm\\node_modules',
101 verbose linkStuff   true,
101 verbose linkStuff   'C:\\Users\\Владимир\\AppData\\Roaming\\npm\\node_modules' ]
102 info linkStuff zephir@0.1.3
103 verbose linkBins zephir@0.1.3
104 verbose linkMans zephir@0.1.3
105 verbose rebuildBundles zephir@0.1.3
106 info install zephir@0.1.3
107 info postinstall zephir@0.1.3
108 verbose unsafe-perm in lifecycle true
109 info zephir@0.1.3 Failed to exec postinstall script
110 verbose unlock done using C:\Users\Владимир\AppData\Roaming\npm-cache\_locks\zephir-9b7e4a4beba5c770.lock for C:\Users\Владимир\AppData\Roaming\npm\node_modules\zephir
111 verbose stack Error: zephir@0.1.3 postinstall: `./install`
111 verbose stack Exit status 1
111 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
111 verbose stack     at EventEmitter.emit (events.js:110:17)
111 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
111 verbose stack     at ChildProcess.emit (events.js:110:17)
111 verbose stack     at maybeClose (child_process.js:1008:16)
111 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
112 verbose pkgid zephir@0.1.3
113 verbose cwd C:\Users\Владимир
114 error Windows_NT 6.3.9600
115 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "zephir"
116 error node v0.12.0
117 error npm  v2.5.1
118 error code ELIFECYCLE
119 error zephir@0.1.3 postinstall: `./install`
119 error Exit status 1
120 error Failed at the zephir@0.1.3 postinstall script './install'.
120 error This is most likely a problem with the zephir package,
120 error not with npm itself.
120 error Tell the author that this fails on your system:
120 error     ./install
120 error You can get their info via:
120 error     npm owner ls zephir
120 error There is likely additional logging output above.
121 verbose exit [ 1, true ]
122 verbose unbuild node_modules\zephir
123 info preuninstall zephir@0.1.3
124 info uninstall zephir@0.1.3
125 verbose unbuild rmStuff zephir@0.1.3 from C:\Users\Владимир\AppData\Roaming\npm\node_modules
126 info postuninstall zephir@0.1.3
127 verbose gentlyRm vacuuming C:\Users\Владимир\AppData\Roaming\npm\node_modules\zephir
128 silly gentlyRm purging C:\Users\Владимир\AppData\Roaming\npm\node_modules\zephir
129 silly gentlyRm quitting because other entries in C:\Users\Владимир\AppData\Roaming\npm\node_modules
```

**Comment by nkt** [comment]
Does Zephir itself works correctly on windows?

**Comment by vladimmi** [comment]
Yes

**Comment by nkt** [comment]
Ok, I'll try to fix this.
